### ISSUE TITLE
Command-line tool

### ISSUE THREAD

**Issue by sergeevabc** [cristalhq/fastid#2]
Dear @cristaloleg,
I'm not sure how to appreciate the beauty of your solution without being able to run it on Windows as a binary that produces the result. E.g. check [ULID](https://github.com/oklog/ulid/) and [CUID](https://github.com/xaevik/cuidgen)v2

```console
$ ulid.exe
01GPR0A4J919E253QDAGVR8MK7

$ cuidgen.exe
gib227a07c6a1njttd9jn982
```

**Comment by cristaloleg** [comment]
Hi, thank you for the kind words.

fastid wasn't created to be persistent. Package was made just to have id for inmem objects.

I will check why it produces diffrent results. Do you've a code that I can debug?

Thanks in advance.

**Comment by cristaloleg** [comment]
Oh, I read you wrong.

You're asking for a cli tool that produces the result.

Well, I think this small tool can be made quite easily, if are eager - fill free to submit a PR. I might take a look today/tomorrow.

**Comment by sergeevabc** [comment]
@cristaloleg, err… I'm not a programmer, but a mere user, who is hardly capable of making a command-line tool at the moment, hence the issue. Only you can do it.

Basically, I'm looking for a tool to generate sequential tags that are shorter than let's say 2023-01-14T215021, which then I can add to some files and folder names. So far I've settled on converting timestamps into Base32, which in this case gives a 9-character value of JCRRCB13D. I wonder what `fastid` could offer.

**Comment by cristaloleg** [comment]
Ok, I will take a look on that. Thanks for the clarification.

**Comment by cristaloleg** [comment]
Oof...I completely missed that, still relevant? 😢

**Comment by sergeevabc** [comment]
@cristaloleg, thank you for taking a moment to revisit this issue.
Indeed, I'm still interested to try your solution under Windows 7 x64.

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by cristaloleg** [comment]
Well, I definitely should start using reminder app.

This should be enough for your case:

```
package main

import (
	"flag"

	"github.com/cristalhq/fastid"
)

func main() {
	epoch := flag.Int64("epoch", fastid.DefaultEpoch, "epoch of the generator")
	workerID := flag.Int("worker_id", 1, "id of the worker")
	flag.Parse()

	gen, err := fastid.NewGenerator(*epoch, *workerID)
	if err != nil {
		panic(err)
	}

	id := gen.Next()
	println(id)
}
```

**Comment by sergeevabc** [comment]
It looks like a code to be compiled, right, @cristaloleg? Sorry, I'm a regular user, not a developer. I'm afraid if I start compiling the code, something will go wrong. Surely you have more experience in compiling than I do. Besides, I've heard that @golang cut off Windows 7 users like me since version 1.21. :(

**Comment by cristaloleg** [comment]
Hey, see https://github.com/cristaloleg/fastid-cli (I've compiled with Go 1.21 which SHOULD work), if not, I will recompile with 1.20.

In any case, please open question in the new repo, I will close this issue. Thanks!

**Comment by sergeevabc** [comment]
@cristaloleg, I downloaded https://github.com/cristaloleg/fastid-cli/blob/main/fastid-cli.exe as you told me, then launched on Windows 7 x64. Alas, it does not work.

![2024-0218-0351 fastid go 121](https://github.com/cristalhq/fastid/assets/373718/a1e1ab2b-075f-41c1-beb6-d99fdf05b70b)

**Comment by cristaloleg** [comment]
Pushed new version, please download new file.

**Comment by sergeevabc** [comment]
> Pushed new version, please download new file.

It works, thank you. It's unusual to see an ID made entirely of numbers.

``` console
$ fastid-cli.exe
904163052843175936
```

**Comment by sergeevabc** [comment]
@cristaloleg, is it possible to get a timestamp from FastID? Something like 

``` console
$ ulid.exe 01JPQP849EHHR294PPFSNWNXE2
Wed Mar 19 17:12:05.678 UTC 2025
```

**Comment by cristaloleg** [comment]
Nope, not right now.
